### ISSUE TITLE
Grouped Joins - How?

### ISSUE THREAD

**Issue by kwaclaw** [jmenziessmith/SqlModeller#2]
How can I build this join (simplified, taken from a more complex query):

    FROM eqReq.LineItemMaster lim
    INNER JOIN (
        eqReq.Compendium cp INNER JOIN eqReq.CompendiumEntry ce ON cp.Id = ce.CompendiumId
    ) ON lim.CompendiumId = cp.Id

The join inside the parentheses has priority, and this can make a difference to the query result.
See http://www.bennadel.com/blog/1059-grouping-join-clauses-in-sql.htm

**Comment by jmenziessmith** [comment]
Hi, I was not aware that joining this way is supported by sqlserver so unfortunately there's currently no support for grouped joins, but it should be easy to add a new type of join if you wish to contribute.

Alternatively does a common table expression help?

**Comment by kwaclaw** [comment]
I think a nested select might help, but it would complicate things. (See the link above).
But the grouped join is certainly the most elegant way.

Should I find the time to add that join type (is it really a join type?) I'll contribute.

**Comment by jmenziessmith** [comment]
please give [this ](https://github.com/jmenziessmith/SqlModeller/commit/e40cf71491e75d5d2d70feac2ab89f79c9c353bc)a try and let me know if it works
