### ISSUE TITLE
Unions - How?

### ISSUE THREAD

**Issue by kwaclaw** [jmenziessmith/SqlModeller#3]
Is support for UNION and UNION ALL planned?

**Comment by jmenziessmith** [comment]
Hi Karl, 
I have just added support for unions and updated the nuget package.

```
            var selectQuery = new SelectQuery().SelectAll().From(firstTable)
            .UnionAll(new SelectQuery().SelectAll().From(secondTable))
            .Union(new SelectQuery().SelectAll().From(thirdTable))
            .OrderBy(string.Empty, "ProductName");

            var query = new Query().Select(selectQuery);
```

Hope this helps, please let me know how you get on with it

**Comment by kwaclaw** [comment]
Hi Jon, Many thanks for implementing this so quickly.

I think there is a little bit of logic still misising when using the UnionSelectQuery in a CTE.
It fails in the CompileFrom methods because the UnionSelectQuery has NULL for the FROM clause.
Try this test case:

        [Test]
        public void TestUnionCte()
        {

            var firstTable = new Table("t1", "FirstTable");
            var secondTable = new Table("t2", "SecondTable");
            var thirdTable = new Table("t3", "ThirdTable");

            var selectQuery = new SelectQuery().SelectAll().From(firstTable)
            .UnionAll(new SelectQuery().SelectAll().From(secondTable))
            .Union(new SelectQuery().SelectAll().From(thirdTable));

            var cte = new CommonTableExpression { Alias = "Cte", Query = selectQuery };

            var query = new Query();
            query.CommonTableExpressions.Add(cte);
            query.SelectQuery = new SelectQuery()
                .From(cte.Alias, cte.Alias)
                .Select("ProductName")
                .OrderBy(string.Empty, "ProductName");

            
            var compiled = query.Compile(false);
             
            Console.WriteLine(compiled.Sql);
        }

**Comment by jmenziessmith** [comment]
thanks for pointing this out. should now be fixed ([commit](https://github.com/jmenziessmith/SqlModeller/commit/d6470470a4754ca876739a67e8310689bcc5963))
